### ISSUE TITLE
ScreenPy Playwright can't launch multiple browsers.

### ISSUE THREAD

**Issue by perrygoy** [ScreenPyHQ/screenpy_playwright#3]
If you try to have multiple Actors who can all `BrowseTheWebSynchronously`, you get a problem:
```python
>>> from screenpy_playwright.abilities import BrowseTheWebSynchronously
>>> NumbuhOne = Actor.named("NumbuhOne").who_can(BrowseTheWebSynchronously.using_firefox())
>>> NumbuhTwo = Actor.named("NumbuhTwo").who_can(BrowseTheWebSynchronously.using_firefox())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/perry/Documents/git/ScreenPyHQ/screenpy_playwright/screenpy_playwright/abilities/browse_the_web_synchronously.py", line 28, in using_firefox
    playwright = sync_playwright().start()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/perry/Documents/git/ScreenPyHQ/screenpy_playwright/env/lib/python3.12/site-packages/playwright/sync_api/_context_manager.py", line 84, in start
    return self.__enter__()
           ^^^^^^^^^^^^^^^^
  File "/Users/perry/Documents/git/ScreenPyHQ/screenpy_playwright/env/lib/python3.12/site-packages/playwright/sync_api/_context_manager.py", line 47, in __enter__
    raise Error(
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

This stems from the ability trying to start up another `playwright` instance while the first is already running. We can probably fix this by just storing the `playwright` instance on the class.

**Comment by perrygoy** [comment]
(Note that this issue was raised by Victor over on the Indie Testing Community Slack, thanks Victor!)

**Comment by perrygoy** [comment]
Fixed!
